openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/symphony-oualidmanai/brewery/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/symphony-thibault/brewery/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Brewery API
  contact:
    email: thibault.pensec@symphony.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: beers
    description: Beers management
paths:
  '/v1/beers':
    get:
      tags:
        - beers
      summary: list beers
      operationId: listBeers
      description: |
        List available beers from the brewery
      responses:
        '200':
          description: list of available beers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Beer'
  '/v1/beers/{id}':
    get:
      tags:
        - beers
      summary: get single beer
      operationId: getBeer
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: string
      description: |
        Bla bla bla
      responses:
        '200':
          description: get single beer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Beer'
components:
  schemas:
    Beer:
      type: object
      required:
        - id
        - name
        - color
      properties:
        id:
          type: string
          format: uuid
          example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
        name:
          type: string
          example: Leffe